server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: giangdh1
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: giangdo456@gmail.com
    password: "kzgx ycmc ivlc ovwt"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcnNhAAAAAwEAAQAAAgEAwt1DFDeVbKnESSYDVJsvm473zzelW0BhAZXGHLqgCM1/6w2WrvArranfU02q0F+laormY49hSUn7NUT2Uid5sn6YEJRUcySj/qwhJzHwtKlQAxEcEcl99lwo5w2pfO3Nlk5+USnYfmHezMvIlu6GNMZbZ63a4ApAGohgT+7c7hkr1DBw2ff+JpkUBSLYnnUN1wgxGugpLCrmjpnrTrwGVOxrN064mvqzWYrApLByWv2kIVkeU/l2gcGHsMHr8eFpEpqG5FG66BT2zu7RKOOli9B5zQffOsW7Ot+KvJRTwfkDaFXoyb5HRWWMxu4iNdl5upRPxZ+qyMYSSOgi4OEDgVsybBbPBU9N6648Z2iaENoVSjpGpBT5cwcosqxqGbg7q3WUbAfmXYZM6nH+hED88FvN3kxTrkN0B46qCgiFb4mGyzfSM6++hTQzRgMWoGtHpyYL2RX2rVB+GWQ5gnrl8vZVzi88TcPgmVwqnJ0fJSPnPJw/5OOvCFEzfK8hXmL1STjBFO2XjEaB4mXx/5hiMadb/rDO/oRC3chmwfyLQSoibheCgj907WXourUyNBo4WD3tpG2POAkiZHssgZEXGciDFXZhlQyrwtwVY8i5dyOlM1p3zgwZdO/Opu9hT3Q+C9oqqgKqJHTBSnpRpJO3Bv/xSCQ3H+UmTEn7aGU8MI8AAAdYkgCC25IAgtsAAAAHc3NoLXJzYQAAAgEAwt1DFDeVbKnESSYDVJsvm473zzelW0BhAZXGHLqgCM1/6w2WrvArranfU02q0F+laormY49hSUn7NUT2Uid5sn6YEJRUcySj/qwhJzHwtKlQAxEcEcl99lwo5w2pfO3Nlk5+USnYfmHezMvIlu6GNMZbZ63a4ApAGohgT+7c7hkr1DBw2ff+JpkUBSLYnnUN1wgxGugpLCrmjpnrTrwGVOxrN064mvqzWYrApLByWv2kIVkeU/l2gcGHsMHr8eFpEpqG5FG66BT2zu7RKOOli9B5zQffOsW7Ot+KvJRTwfkDaFXoyb5HRWWMxu4iNdl5upRPxZ+qyMYSSOgi4OEDgVsybBbPBU9N6648Z2iaENoVSjpGpBT5cwcosqxqGbg7q3WUbAfmXYZM6nH+hED88FvN3kxTrkN0B46qCgiFb4mGyzfSM6++hTQzRgMWoGtHpyYL2RX2rVB+GWQ5gnrl8vZVzi88TcPgmVwqnJ0fJSPnPJw/5OOvCFEzfK8hXmL1STjBFO2XjEaB4mXx/5hiMadb/rDO/oRC3chmwfyLQSoibheCgj907WXourUyNBo4WD3tpG2POAkiZHssgZEXGciDFXZhlQyrwtwVY8i5dyOlM1p3zgwZdO/Opu9hT3Q+C9oqqgKqJHTBSnpRpJO3Bv/xSCQ3H+UmTEn7aGU8MI8AAAADAQABAAACAGEzo8lK7LN2f54JYzHp8zaCe2SXGlnJZFo5Dsi34ypg78UdUyPSU8dd7DOOk307qLTbso7JL7syNyfcTY6veEosUcg7ZWDGTzOzQxpdE/faWToeZ8ULoFSqphCTRQ83RA0M/H+aAw8P3OaFZHq9Yp6ir2epVnvZQR67Fmfo+7WdQrqmqzRfOxyf0Ve6iRmJxCyWPoBwfFE22Ska6ECvE+16vQSqtPVBxwMMbon4JiLzUNL9tF4pGw8grYHjScGvMg2AnXb4ueYYxwB0KkteOu7iQE+g9J5JkdqNNZRZ3OnuP9/ksqknzD92p2F32gLIh6slXiFzQurBus85VGSeeXNG+KXKYoHOpgeQjgB8gC++KHhJgtteWalLtp1FUMW3umZ9uMbBEJ7YU0/kdu+3RuPB8GajTnLKux55NXRD1FyFld2HtVZRcdTz/ALOVprrkBQarrPxRnA/f+XaBrv9k03o2nD8zBYuwBVBDeDs/7D1rlBTT0zZxds/pxD7r7/R29M0oHwmGd1pRsb1gqAcyaT/O16Cp5aqAloKTcCQg4R7dK2ZJaV/bf/0KtbSwNlDryPoSjeFqM+9a9OQlY+8jdk1bJmmYfsYSXmsmiATvnxta4DG0CPPHrDVtnoC/byFo4s5Y4bEFp0NGruH2SYiJPPtpPqG4PXvFX8Ayvu2kQdRAAABAQC+Agc++aZdTXSeyyWxL3O27m8HRxRuUnCPbXFw4w/Z1gE4b18hW4EIc83mXwIVWTn8ZnHAWNpd5enzrm76VEkdPXg0xfLNnjUk6XkpbODLaH9nuR/9fqri+v89mE/+1EdK1I551Bfj1DbbcjOGu2W/wXGIdSBGVJHOFqXdvaeV2G+9LwmS9escGIK4WOkP+Cv9Ne/RqmZgkT9VhBHDRNq++YY8g6W0t2b1XN+X+HpNlfPBzGeTJtuiAN1QIlOChmT5VK+NiF9b0y30iPLK932jwdzilq7fG94iOQ8PT3nX/+oAOSnzdo8ChyNrj4GxPm/RKIQl4++c24MHVILFqAckAAABAQDt5arqwv9bpif4tjS6lHN7BGyoaNodTtKGO/7V7Agaa77emgCAELv7e9dok8TYEiZu/WuVcvpjZoZW+zDi6p++aQ/HuZGSyy1Up7byU2HTHDUZUcjLdnWfkWwMQnGOsHGwyHSevfdY3rb36Wpa7MYtr5X5XtxrMJf0Zp3T7KAaVqYjvamPBbkzsqUyEVV4McroZ7mQv4NP1LazVgmTbZ1BDU45aNINtkgzvh8MlsZqgjqREQXujzDoHsGVvXSuHkDpb3kFYuoYooPrUqU7x3YvPPfSEyyHLWZzDPxdvImgA1VgudAVseX2cQbdoATzGy6/b6c0XgocyhSG39NyYfd3AAABAQDRsUwhkyDXhSp4LChu2kTPGdYTZWvMmqmbpvXqYfKiLE+6Xy0wpm9UuDel4zeEvlEaeZlQrw3Py+dYdrZuJzOLOoaHHr+9NXLYIyyw4r8HGC0fveNXgUdIbYYmiilgTMBJJM7+qHXMNdOhGYhwSNyTCXDTQuMD0NXi2uIDmZPt7Mn3gEjurn1K7J5nxrdFRTGvSBwTUZ5aYPMKcr+k73YjmgGyTNmujLpmlo6dk3LZwJjMESR31w2ufZxMpOKhUi8WZUVqrZs8C2xT6MoUJDTPylgo+2b5Lv7YikHJrPu96SevrfpjRKYtP+6EV52EwOpoO7aJIFEB5fh0ckoYuYWpAAAAG2dpYW5nX8SQ4buXQERFU0tUT1AtUlMwVFBTOAECAwQFBgc="

# IP allowed
allowed:
  ips:
    - "192.168.56."
    - "192.168.9."
  mac:
    - "98-E7-43-0C-3C-2C"
    - "0A-00-27-00-00-12"
    - "AC-D5-64-90-93-CD"
